[database]
uri = "mongodb://localhost/liquality"
debug = true

[application]
apiPort = 3030

[worker]
maxJobRetry = 5
jobRetryDelay = "5 seconds"
# jobReporter = "/Users/user/slack.js"

[rate]
  updateInterval = "5 minutes"

  [rate.pairs.BTC-ETH]
  provider = "coinbase-pro"
  type = "pair"
  flip = true

  [rate.pairs.ETH-BTC]
  provider = "coinbase-pro"
  type = "pair"

  [rate.pairs.DAI-BTC]
  provider = "coinmarketcap"
  type = "pair"

[rateProvider]
  [rateProvider.coinmarketcap]
  apiKey = ""

[assets]
  [assets.BTC]
  network = "bitcoin_regtest"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTime = "5 seconds"
    [assets.BTC.rpc]
    url = "http://localhost:18443"
    username = "bitcoin"
    password = "local321"

  [assets.ETH]
  blockTime = "5 seconds"
    [assets.ETH.scraper]
    url = "http://localhost:8545"

    [assets.ETH.rpc]
    url = "http://localhost:8545"

  [assets.DAI]
  type = "ERC20"
  blockTime = "5 seconds"
  contractAddress = "0xf6316f11abfc4c6bd72bcb893a52d88fbb22a719"
    [assets.DAI.rpc]
    url = "http://localhost:8545"
