[database]
uri = "mongodb://localhost/liqualitytest"
debug = false

[redis]
uri = "redis://localhost:6379/1"

[application]
apiPort = 3030
queuePassword = "test123"
queuePasswordRW = "secretRWTest123"
quoteExpirationInSeconds = 1800
nodeSwapExpirationDurationInSeconds = 2700
swapExpirationDurationInSeconds = 3600

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'
bearer = '58da74ef560e5578cb46219b7818d7c2'

[threshold]
manualAboveFromAmountUsd = 5000

# [vault]
# endpoint = "http://127.0.0.1:8200"
# mnemonicsBasePath = "secret/data/agent/mainnet/production/mnemonics"

[worker]
minConcurrentSwaps = 3
killswitch = 'pm2 stop "Worker"'

[assets]
  [assets.BTC]
  network = "bitcoin_regtest"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.BTC.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.BTC.api]
    url = "http://localhost:3002/"
    [assets.BTC.batchApi]
    url = "http://localhost:9090/"
    [assets.BTC.rpc]
    url = "http://localhost:18443/"
    user = "admin1"
    password = "123"

  [assets.ETH]
  network="local"
  blockTimeInSeconds = 5
  defaultFee = "average"
    [assets.ETH.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.ETH.scraper]
    url = "http://localhost:8080"
    [assets.ETH.rpc]
    url = "http://localhost:8545"

  [assets.DAI]
  network="local"
  type = "ERC20"
  blockTimeInSeconds = 5
  contractAddress = "0x094cdd8e19b97505869c87a995a972c4df7f69a8"
  defaultFee = "average"
    [assets.DAI.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.DAI.scraper]
    url = "http://localhost:8080"
    [assets.DAI.rpc]
    url = "http://localhost:8545"

  [assets.RBTC]
  blockTimeInSeconds = 20
  network = "rsk_testnet"
  defaultFee = "average"
  pegWith = "BTC"
    [assets.RBTC.rpc]
    url = "https://public-node.testnet.rsk.co"
    [assets.RBTC.scraper]
    url = "https://liquality.io/rsk-testnet-api/"
    [assets.RBTC.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"

  [assets.SOV]
  blockTimeInSeconds = 20
  network = "rsk_testnet"
  defaultFee = "average"
  contractAddress = "0x6a9A07972D07E58f0daF5122D11e069288A375fB"
    [assets.SOV.rpc]
    url = "https://public-node.testnet.rsk.co"
    [assets.SOV.scraper]
    url="https://liquality.io/rsk-testnet-api/"
    [assets.SOV.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
