[database]
# ---------------------------------------------- Connection settings for MongoDB
# Provide either (uri will take precedence):
#
# uri        - A full mongodb connection uri (see: https://docs.mongodb.com/manual/reference/connection-string/)
#              e.g.
#              mongodb://admin:password@127.0.0.1:27017/liquality?authSource=admin
#
#    -or-
#
# host       - The db hostname/IP
# port       - The db port (optional)
# dbname     - The db name (optional)
# username   - The username for auth (optional, leave blank if no auth)
# password   - The password for auth (optional, leave blank if no auth)
# authdbname - The auth db name (optional with auth, leave blank if no auth)
# ------------------------------------------------------------------------------
# Other options:
#
# debug      - true|false (Enables mongodb debug)
#
# [database.migrate]
# log        - true|false (Enables migrator logging, for short messages, default: true)
# verbose    - true|false (Enables verbose migrator logging, for debugging, default: false)
# force      - true|false (Forces refresh of assets/markets data, default: false)
# ------------------------------------------------------------------------------
debug = false
# uri = "mongodb://demo:demo-password@docker.for.mac.host.internal:27017/rickandmorty?authSource=test"
# uri = "mongodb://admin:admin-password@docker.for.mac.host.internal:27017/liquality?authSource=admin"
host = "10.0.1.5"
port = "27017"
dbname = "liquality"
username = "liquality"
authdbname = "admin"
  [database.migrate]
  log = true
  verbose = false
  force = false

[application]
apiPort = 3030
swapExpirationDurationInSeconds = 3600
nodeSwapExpirationDurationInSeconds = 1800

[auth]
cookieSecret = '58da74ef560e5578cb46219b7818d7c2'
cookieMaxAgeMs = 86400000
simplePassword = '25ec02267950f537347b4a7c02b00ced'

[threshold]
manualAboveFromAmountUsd = 5000

[worker]
maxJobRetry = 5
jobRetryDelay = "5 seconds"
backendJobRetryDelay = "5 seconds"
minConcurrentSwaps = 3
defaultLockLifetimeInMs = 120000 # 2 min
killswitch = 'pm2 stop "Worker"'

[assets]
  # [assets.BTC]
  # network = "bitcoin_regtest"
  # addressType = "bech32"
  # swapMode = "p2wsh"
  # feeNumberOfBlocks = 2
  # blockTime = "5 seconds"
  # defaultFee = "average"
  #   [assets.BTC.wallet]
  #   type = "js"
  #   mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
  #   [assets.BTC.api]
  #   url = "http://localhost:3002/" # vulpemventures/electrs:latest (3rd party)
  #   [assets.BTC.batchApi]
  #   url = "http://localhost:9090/" # electrs-batch-server.dockerfile (inside docker dir)
  #   [assets.BTC.rpc]
  #   url = "http://localhost:18443/" # vulpemventures/bitcoin:latest (3rd party)
  #   user = "admin1"
  #   password = "123"

  [assets.ETH]
  network="local"
  blockTime = "5 seconds"
  defaultFee = "average"
    [assets.ETH.wallet]
    type = "js"
    mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
    [assets.ETH.scraper]
    url = "http://localhost:8080" # ethereum-scraper
    [assets.ETH.rpc]
    url = "http://localhost:8545" # Infura (3rd party)

  # [assets.DAI]
  # network="local"
  # type = "ERC20"
  # blockTime = "5 seconds"
  # contractAddress = "0x094cdd8e19b97505869c87a995a972c4df7f69a8"
  # defaultFee = "average"
  #   [assets.DAI.wallet]
  #   type = "js"
  #   mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
  #   [assets.DAI.scraper]
  #   url = "http://localhost:8080" # ethereum-scraper
  #   [assets.DAI.rpc]
  #   url = "http://localhost:8545" # Infura (3rd party)

  # [assets.RBTC]
  # blockTime = "20 seconds"
  # network = "rsk_testnet"
  # defaultFee = "average"
  # pegWith = "BTC"
  #   [assets.RBTC.rpc]
  #   url = "https://public-node.testnet.rsk.co" # RSK service (3rd party)
  #   [assets.RBTC.scraper]
  #   url = "https://liquality.io/rsk-testnet-api/" # ethereum-scraper
  #   [assets.RBTC.wallet]
  #   type = "js"
  #   mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"

  # [assets.SOV]
  # blockTime = "20 seconds"
  # network = "rsk_testnet"
  # defaultFee = "average"
  # contractAddress = "0x6a9A07972D07E58f0daF5122D11e069288A375fB"
  #   [assets.SOV.rpc]
  #   url = "https://public-node.testnet.rsk.co" # Infura (3rd party)
  #   [assets.SOV.scraper]
  #   url="https://liquality.io/rsk-testnet-api/" # ethereum-scraper
  #   [assets.SOV.wallet]
  #   type = "js"
  #   mnemonic = "piece effort bind that embrace enrich remind powder sudden patient legend group"
