name: 'Docker build, tag, push to ECR (personal)'

on:
  push:
    branches:
      - dockerized
    paths:
      - 'env/personal/**'
      - 'src/**'
      - '.github/workflows/docker-push-to-personal.yml'

env:
  ENV_ALIAS: 'personal'
  AWS_REGION: 'us-east-2'
  IMAGE_NAME: 'atomicagent-personal'
  IMAGE_TAG: 'latest'
  DOCKERFILE_PATH: 'service.dockerfile'

jobs:
  docker-deploy:
    name: 'Build & Deploy Image'
    runs-on: ubuntu-latest
    environment: personal

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Load AWS credentials (this is the ecs-service service account)
      - name: Load AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      # Login to ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build, tag, and push Docker image to ECR
      - name: Build, tag, push image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # IMAGE_TAG: ${{ github.sha }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Building and tagging Docker image ($IMAGE_NAME)"
          docker build -f $DOCKERFILE_PATH --build-arg ENV_ALIAS=${ENV_ALIAS} --build-arg DB_PASSWORD=${DB_PASSWORD} -t $IMAGE_NAME . --no-cache
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          echo "Pushing image to registry: $REGISTRY_URI/$IMAGE_NAME"
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # Trigger update to ECS cluster
      - name: Update ECS
        id: update-ecs
        run: |
          echo "Assuming deployment role for ECS update"
          source ./bin/aws-assume-role.sh "${AWS_REGION}" "${{ github.sha }}" "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          aws ecs update-service --cluster ${IMAGE_NAME} --service ${IMAGE_NAME} --force-new-deployment
